### ISSUE TITLE
Interactive map icons move around when you move around the world map

### ISSUE THREAD

**Issue by FallenAngelII** [Akebi-Group/Akebi-GC#93]
And they stay permanently misaligned. I have kept the "Fix item positions" options ticked in. Doesn't help.

**Comment by G1DE30N** [comment]
This bug is fixed. You need update cheat to latest commit.

**Comment by FallenAngelII** [comment]
Is that different from this one? https://github.com/Akebi-Group/Akebi-GC/releases/tag/v0.7.5

I've been using that all along and still getting the bug.

**Comment by CallowBlack** [comment]
Can you give video or something with this bug?

**Comment by FallenAngelII** [comment]
Here's a video: https://www.mediafire.com/file/lj1ohlr9rgf42cw/Desktop+Screenshot+2022.06.04+-+18.40.33.63.mkv/file

Please ignore the fact that there's a black bar on the left and that the Filters menus are in the black part. That's just what it looks like when I CTRL + ALT for full screen after playing in windowed mode. But the glitch happens even if I start out in full screen move.

**Comment by CallowBlack** [comment]
Hmm, weird. Due to capture, I can't be sure what it is? Would be better if you do capture with normal interface without the black line. Yeah, I saw that marks moving, but it seems too odd. Actually, marks can move a little, it's just a glitch that didn't impact on position. Also, you can check this video, maybe it shows your problem?
https://drive.google.com/file/d/1XqBUuzZIuZ8jv47kSGGjwmednqYmjnrP/view

**Comment by FallenAngelII** [comment]
I'll try and capture that later. The problem is that for me, when the icons move around, they get don't re-align later. So after a while, everything is not where it should be. Icons can be 50-100 meters off.

**Comment by FallenAngelII** [comment]
Here's a regular video without the black border on the left: https://www.mediafire.com/file/9a072p4zicdbd56/Genshin_Impact_2022.06.11_-_00.42.50.08.mkv/file

**Comment by CallowBlack** [comment]
Very odd. Seems that problem is in PS version. I don't think that in the near future I can fix it.

**Comment by FallenAngelII** [comment]
Aah, bummer. I assume by PS you don't mean Playstation but something else.

**Comment by CallowBlack** [comment]
> Aah, bummer. I assume by PS you don't mean Playstation but something else.

Nope, I mean Playstation.

**Comment by FallenAngelII** [comment]
Oh. I'm playing on PC. I'm just using an Xbox One controller.

**Comment by CallowBlack** [comment]
> Oh. I'm playing on PC. I'm just using an Xbox One controller.

What's your resolution?

**Comment by kaninayut** [comment]
1366x768 and higger will fine but if lower like 1280 this bug will appear ✌️, that is what i figure it out

**Comment by FallenAngelII** [comment]
This happens at all resolutions for me. I have a 20:9 screen so the one I normally play at 2560x1440 windowed, but it also happens with . The video shown above was captured at 1920x1080.

I figured something out just now. I've been suspecting it for a while, but I just confirmed it. When I switched to Keyboard (+Mouse) controls, the Interactive Map works as it should (currently in 2560x1440 windowed). Somehow, the glitch only happens when playing using a controller.

**Comment by Lunairayz** [comment]
> I confirm this behavior - when using the gamepad as a control option, the interface is rendered differently, and thus for some reason the icons "floating"

YEP, i have 1920x700 (on a 1920x1080 display) for fps, and this makes icons fly here and there
